### ISSUE TITLE
Failed to load the particle-dev-libraries package

### ISSUE THREAD

**Issue by ryan-lee-okp** [spark/particle-dev-libraries#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [particle-dev-libraries](https://github.com/spark/particle-dev-libraries) package 0.2.30

### Stack Trace

Failed to load the particle-dev-libraries package

```
At Cannot find module './lib/api/node.js'

Error: Cannot find module './lib/api/node.js'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12454:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11798:33)
    at /packages/particle-dev-libraries/node_modules/babel-core/index.js:1:173)
    at /packages/particle-dev-libraries/node_modules/babel-core/index.js:3:3)
    at Module.get_Module._compile (<embedded>:11838:36)
    at Object.value [as .js] (<embedded>:12090:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11798:33)
    at Object.transpile (/packages/particle-dev-libraries/node_modules/atom-babel6-transpiler/lib/index.js:50:19)
    at PackageTranspilationRegistry.transpileWithPackageTranspiler (<embedded>:39673:39)
    at Object.compile (<embedded>:39593:29)
    at compileFileAtPath (<embedded>:11948:37)
    at Object.value [as .js] (<embedded>:12089:26)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (<embedded>:96:26)
    at Package.requireMainModule (<embedded>:75718:33)
    at measure (<embedded>:75079:22)
    at Package.measure (<embedded>:75024:25)
    at Package.load (<embedded>:75065:16)
    at PackageManager.loadAvailablePackage (<embedded>:26199:16)
    at config.transact (<embedded>:26112:20)
    at Config.transact (<embedded>:22777:20)
    at PackageManager.loadPackages (<embedded>:26110:23)
    at loadStatePromise.loadState.then (<embedded>:1080:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
particle-dev-cloud-functions 0.2.0 
particle-dev-cloud-variables 0.2.0 
particle-dev-complete 1.0.2 
particle-dev-libraries 0.2.30 
particle-dev-profiles 0.2.3 
```

**Comment by suda** [comment]
@kwayun0138 hmm can you try to uninstall and install the package again? Looks like it's missing some core files.
